from django.utils.translation import ugettext as _

str_deposit = _('deposit')
str_send = _('send')
str_balance = _('balance')
str_more = _('more')
str_done = _('done')

str_help_message_first_half = _("To deposit money into your account, reply 'deposit (amount in PHP) (BPI or BDO)'. For more instructions reply 'more'")
str_help_message_second_half =_("To check your account balance, reply 'balance'. To pay your loan, reply 'send (amount) @mentors'.")
str_create_account = _("To create an account create a username. (Example: ilovecats12)")
str_welcome_username_taken = _("Welcome!\nYou're user name is @%s\n(Sadly, @%s was already taken))")
str_welcome = _("Welcome @%s!\n%s")
str_username_not_found = _("Sorry, %s was not found.\nPlease check the username\n: (")
str_successful_deposit = _("You have successfully deposited {} into your wallet. Current balance: {}. To pay your loan, reply 'send (amount) @mentors'.")
str_balance_message = _("You have {} available, with {} pending.")
str_sent_message = _("Sent {} to {} successfully!")
str_deposit_bdo_message = _("Go to any BDO branch & deposit {} into this account: Account Name: BETUR INC. Account Number: 008178000421 Account Type: CURRENT. Reply 'done' when done.")
str_deposit_bpi_message = _("Go to any BPI branch & deposit {} into this account: Account Name: BETUR INC. Account Number: 8371-0022-36 Account Type: CURRENT. Reply 'done' when done.")
str_deposit_message = _("You have successfully deposited {} into your account. Current balance: {}. To pay your loan, reply 'send (amount) @mentors'.")

str_error_monetary_deposit = _("Error: Enter a numeric amount to deposit. To deposit money reply 'deposit (amount in PHP) (BPI or BDO)'.")
str_error_deposit_negative_amount = _("Error: The amount to deposit must be positive")
str_error_send_negative_amount = _("Error: The amount to send must be positive")
str_error_username = _("Error: The deposit receiver must be a username that starts with @")
str_error_deposit_bdo_bpi = _("Error: To deposit money reply 'deposit (amount in PHP) (BPI or BDO)' where BPI or BDO is the bank you\'re depositing at.")
str_error_monetary_send = _("Error: Enter a number amount to send.")
str_error_funds = _("Error: Not enough funds")
str_error_pending_deposit = _("Error: Deposit already started for {}. Reply 'done' after depositing that amount at the location you have chosen.")